controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
api_login_check:
    path: /api/login_check

api_tasks_list:
    path: api/tasks
    controller: App\Controller\TaskController::index
    methods: GET

show_task:
      path: api/tasks/{id}
      controller: App\Controller\TaskController::showTask
      methods: [GET]

new_task:
      path: api/tasks
      controller: App\Controller\TaskController::newTask
      methods: [POST]

edit_task:
      path: api/tasks/{id}
      controller: App\Controller\TaskController::editTask
      methods: [PUT]

delete_task:
      path: api/tasks/{id}
      controller: App\Controller\TaskController::deleteTask
      methods: [DELETE]

